### ISSUE TITLE
How do I use this program?

### ISSUE THREAD

**Issue by haruhir0219** [Meetem/RazerBladeSharp#2]
Sorry, not really a issue but couldn't fin any way to contact you so I'll write here.

I'm not familiar with C#, USB interface or any of that stuff. But I'm looking for any alternative to crappy mess that is Synapse. Especially fan speed stuff. 

Do I need some other program to use / load this program?

**Comment by Meetem** [comment]
Hey, yes, I do have sample program, but it’s a command line utility. Looks
like I need a make a gui one for those who are interested
